import Head from "next/head";
import Header from "../components/Header";

export default function Home() {
    return (
        <div className="h-screen bg-[#feba07]">
            <Head>
                <title>Cheap Adviser</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/elephant.png" />
            </Head>
            {/* Header */}
            <Header />
            {/* CustomerGroup */}
            {/* Reasons */}
            {/* Services */}
            {/* Schools */}
            {/* OnlineCourses */}
            {/* Feedbacks */}
            {/* Teachers */}
            {/* Contact */}
            {/* Prices */}
            {/* Photos */}
            {/* Career */}
            {/* Blogs */}
            {/* Links */}
        </div>
    );
}
